# Generated by Django 4.0.1 on 2022-01-08 10:16
import datetime

from django.db import migrations
import csv
from django.db import transaction


def load_data(apps, schema_editor):
    Data = apps.get_model('api', 'Data')
    data_objs = []
    with open('./data/dataset.csv', "r") as csv_file:
        data = csv.reader(csv_file, delimiter=",")
        data = list(data)
        for row in data[1:]:
            print(row)
            obj_data = {
                'date': row[0],
                'channel': row[1],
                'country': row[2],
                'os': row[3],
                'impressions': int(row[4]),
                'clicks': int(row[5]),
                'installs': int(row[6]),
                'spend': float(row[7]),
                'revenue': float(row[8])
            }
            obj = Data(**obj_data)
            print(obj)
            data_objs.append(obj)
    with transaction.atomic():
        Data.objects.bulk_create(data_objs)


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_data)
    ]
